version: "3.8"

services:
  fizz-buzz:
    image: spelmezan/fizz-buzz-rest-server:0.1.0
    command: [ "-redisEndpoint", "redis:6379", "-waitForRedis=false" ]
    networks:
      fizz-buzz:
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:6.2.5-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      fizz-buzz:
    volumes:
      - data:/data

networks:
  fizz-buzz:

volumes:
  data:
