version: "3.8"

services:
  fizz-buzz:
    image: danhspe/fizz-buzz-rest-server:${FIZZ_BUZZ_TAG}
    command: [ "-redisEndpoint", "redis:6379", "-waitForRedis=false" ]
    networks:
      fizz-buzz:
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:${REDIS_TAG}
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      fizz-buzz:
    volumes:
      - data:/data

networks:
  fizz-buzz:

volumes:
  data:
