// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fizzbuzz.proto

package fizzbuzz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FizzBuzzRequest struct {
	Int1                 int64    `protobuf:"varint,1,opt,name=int1,proto3" json:"int1,omitempty"`
	Int2                 int64    `protobuf:"varint,2,opt,name=int2,proto3" json:"int2,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Str1                 string   `protobuf:"bytes,4,opt,name=str1,proto3" json:"str1,omitempty"`
	Str2                 string   `protobuf:"bytes,5,opt,name=str2,proto3" json:"str2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzRequest) Reset()         { *m = FizzBuzzRequest{} }
func (m *FizzBuzzRequest) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzRequest) ProtoMessage()    {}
func (*FizzBuzzRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bcb06695496ad1, []int{0}
}

func (m *FizzBuzzRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzRequest.Unmarshal(m, b)
}
func (m *FizzBuzzRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzRequest.Marshal(b, m, deterministic)
}
func (m *FizzBuzzRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzRequest.Merge(m, src)
}
func (m *FizzBuzzRequest) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzRequest.Size(m)
}
func (m *FizzBuzzRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzRequest proto.InternalMessageInfo

func (m *FizzBuzzRequest) GetInt1() int64 {
	if m != nil {
		return m.Int1
	}
	return 0
}

func (m *FizzBuzzRequest) GetInt2() int64 {
	if m != nil {
		return m.Int2
	}
	return 0
}

func (m *FizzBuzzRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FizzBuzzRequest) GetStr1() string {
	if m != nil {
		return m.Str1
	}
	return ""
}

func (m *FizzBuzzRequest) GetStr2() string {
	if m != nil {
		return m.Str2
	}
	return ""
}

type FizzBuzzResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzResponse) Reset()         { *m = FizzBuzzResponse{} }
func (m *FizzBuzzResponse) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzResponse) ProtoMessage()    {}
func (*FizzBuzzResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bcb06695496ad1, []int{1}
}

func (m *FizzBuzzResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzResponse.Unmarshal(m, b)
}
func (m *FizzBuzzResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzResponse.Marshal(b, m, deterministic)
}
func (m *FizzBuzzResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzResponse.Merge(m, src)
}
func (m *FizzBuzzResponse) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzResponse.Size(m)
}
func (m *FizzBuzzResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzResponse proto.InternalMessageInfo

func (m *FizzBuzzResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*FizzBuzzRequest)(nil), "fizzbuzz.FizzBuzzRequest")
	proto.RegisterType((*FizzBuzzResponse)(nil), "fizzbuzz.FizzBuzzResponse")
}

func init() { proto.RegisterFile("fizzbuzz.proto", fileDescriptor_34bcb06695496ad1) }

var fileDescriptor_34bcb06695496ad1 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0x47, 0xa9, 0xfb, 0x07, 0x37, 0x07, 0x95, 0x20, 0x92, 0xe3, 0xb2, 0xa7, 0x45, 0xe8, 0x86,
	0x8d, 0x07, 0xf1, 0xda, 0x83, 0x1f, 0x20, 0x47, 0x6f, 0x46, 0xc7, 0x36, 0xd0, 0x36, 0x35, 0x33,
	0x51, 0x98, 0x4f, 0x2f, 0x8d, 0x6d, 0xf7, 0x36, 0xef, 0x31, 0xf0, 0xe3, 0x89, 0x9b, 0x2f, 0xcf,
	0xec, 0x12, 0xf3, 0x69, 0x88, 0x81, 0x82, 0xbc, 0x9e, 0xf9, 0xf0, 0x2b, 0x6e, 0x5f, 0x3d, 0x73,
	0x95, 0x98, 0x2d, 0x7c, 0x27, 0x40, 0x92, 0x52, 0xac, 0x7d, 0x4f, 0x67, 0x55, 0xec, 0x8b, 0xe3,
	0xca, 0xe6, 0x7b, 0x72, 0x46, 0x5d, 0x2d, 0xce, 0xc8, 0x7b, 0xb1, 0x69, 0x7d, 0xe7, 0x49, 0xad,
	0xb2, 0xfc, 0x87, 0xf1, 0x13, 0x29, 0x9e, 0xd5, 0x7a, 0x5f, 0x1c, 0x77, 0x36, 0xdf, 0x93, 0x33,
	0x6a, 0xb3, 0x38, 0x73, 0x78, 0x14, 0x77, 0x97, 0x61, 0x1c, 0x42, 0x8f, 0x20, 0x1f, 0xc4, 0x36,
	0x02, 0xa6, 0x96, 0xf2, 0xf6, 0xce, 0x4e, 0x54, 0xbd, 0xbc, 0x3d, 0xd7, 0x9e, 0x9a, 0xe4, 0x4e,
	0x1f, 0xa1, 0xd3, 0x9f, 0xef, 0x7d, 0x83, 0x03, 0xe8, 0xb1, 0xa1, 0x1c, 0x23, 0xca, 0x08, 0x48,
	0x25, 0x42, 0xfc, 0x81, 0xa8, 0xeb, 0xd0, 0x7a, 0xa7, 0xe7, 0x3e, 0xb7, 0xcd, 0xc1, 0x4f, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0x1b, 0x64, 0x3d, 0x02, 0x01, 0x00, 0x00,
}
